# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1828, 909)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/background/stnm_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QTabWidget::pane { \n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QWidget#tab { \n"
"    border-image: url(:/background/goktulga2.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"QWidget#tab_2 { \n"
"    border-image: url(:/background/goktulga2.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"QWidget#tab_3 { \n"
"    border-image: url(:/background/goktulga2.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"QWidget#tab_4 { \n"
"    border-image: url(:/background/goktulga2.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: lightgray;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.port_comboBox = QtWidgets.QComboBox(self.tab)
        self.port_comboBox.setGeometry(QtCore.QRect(370, 0, 191, 22))
        self.port_comboBox.setStyleSheet("#comboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.port_comboBox.setObjectName("port_comboBox")
        self.port_comboBox.addItem("")
        self.port_comboBox.addItem("")
        self.port_comboBox.addItem("")
        self.port_comboBox.addItem("")
        self.port_comboBox.addItem("")
        self.port_comboBox.addItem("")
        self.port_comboBox.addItem("")
        self.port_comboBox.addItem("")
        self.baud_comboBox = QtWidgets.QComboBox(self.tab)
        self.baud_comboBox.setGeometry(QtCore.QRect(570, 0, 91, 22))
        self.baud_comboBox.setStyleSheet("#comboBox_2{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"")
        self.baud_comboBox.setObjectName("baud_comboBox")
        self.baud_comboBox.addItem("")
        self.baud_comboBox.addItem("")
        self.baud_comboBox.addItem("")
        self.baglan_pushButton = QtWidgets.QPushButton(self.tab)
        self.baglan_pushButton.setGeometry(QtCore.QRect(680, 0, 111, 31))
        self.baglan_pushButton.setStyleSheet("#baglan_pushButton{\n"
"background-color: rgb(255, 231, 226);\n"
"}\n"
"")
        self.baglan_pushButton.setObjectName("baglan_pushButton")
        self.ucusBilgisi_groupBox = QtWidgets.QGroupBox(self.tab)
        self.ucusBilgisi_groupBox.setGeometry(QtCore.QRect(10, 40, 321, 431))
        self.ucusBilgisi_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.ucusBilgisi_groupBox.setObjectName("ucusBilgisi_groupBox")
        self.label_3 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 141, 16))
        self.label_3.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_11 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 121, 16))
        self.label_11.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_11.setObjectName("label_11")
        self.label_21 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_21.setGeometry(QtCore.QRect(10, 390, 146, 16))
        self.label_21.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_21.setObjectName("label_21")
        self.label_5 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_5.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 44, 16))
        self.label_13.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_15.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 36, 16))
        self.label_14.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 141, 16))
        self.label_12.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_12.setObjectName("label_12")
        self.label_32 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_32.setGeometry(QtCore.QRect(10, 190, 111, 16))
        self.label_32.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_32.setObjectName("label_32")
        self.label_16 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 52, 16))
        self.label_16.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_16.setObjectName("label_16")
        self.label_31 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_31.setGeometry(QtCore.QRect(10, 210, 121, 16))
        self.label_31.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_31.setObjectName("label_31")
        self.label_19 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_19.setGeometry(QtCore.QRect(10, 230, 131, 16))
        self.label_19.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_19.setObjectName("label_19")
        self.label_18 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_18.setGeometry(QtCore.QRect(10, 370, 81, 16))
        self.label_18.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_18.setObjectName("label_18")
        self.label_22 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 250, 111, 16))
        self.label_22.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_23.setGeometry(QtCore.QRect(10, 270, 111, 16))
        self.label_23.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_23.setObjectName("label_23")
        self.label_17 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_17.setGeometry(QtCore.QRect(10, 290, 101, 16))
        self.label_17.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_17.setObjectName("label_17")
        self.label_24 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_24.setGeometry(QtCore.QRect(10, 310, 111, 16))
        self.label_24.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.label_25.setGeometry(QtCore.QRect(10, 330, 81, 16))
        self.label_25.setStyleSheet("QLabel {\n"
"  font-size: 14px; /* Yazı tipi boyutunu 24 piksele ayarlar */\n"
"}")
        self.label_25.setObjectName("label_25")
        self.takimNo_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.takimNo_label.setGeometry(QtCore.QRect(120, 30, 161, 16))
        self.takimNo_label.setObjectName("takimNo_label")
        self.enlem_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.enlem_label.setGeometry(QtCore.QRect(60, 50, 251, 16))
        self.enlem_label.setObjectName("enlem_label")
        self.boylam_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.boylam_label.setGeometry(QtCore.QRect(70, 70, 241, 16))
        self.boylam_label.setObjectName("boylam_label")
        self.irtifa_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.irtifa_label.setGeometry(QtCore.QRect(50, 90, 251, 16))
        self.irtifa_label.setObjectName("irtifa_label")
        self.pitch_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.pitch_label.setGeometry(QtCore.QRect(150, 110, 151, 16))
        self.pitch_label.setObjectName("pitch_label")
        self.yaw_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.yaw_label.setGeometry(QtCore.QRect(150, 130, 151, 16))
        self.yaw_label.setObjectName("yaw_label")
        self.roll_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.roll_label.setGeometry(QtCore.QRect(130, 150, 171, 16))
        self.roll_label.setObjectName("roll_label")
        self.yerHizi_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.yerHizi_label.setGeometry(QtCore.QRect(70, 170, 221, 16))
        self.yerHizi_label.setObjectName("yerHizi_label")
        self.batarya_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.batarya_label.setGeometry(QtCore.QRect(120, 190, 181, 16))
        self.batarya_label.setObjectName("batarya_label")
        self.otonomDurumu_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.otonomDurumu_label.setGeometry(QtCore.QRect(130, 210, 171, 16))
        self.otonomDurumu_label.setObjectName("otonomDurumu_label")
        self.kilitlenmeDurumu_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.kilitlenmeDurumu_label.setGeometry(QtCore.QRect(140, 230, 161, 16))
        self.kilitlenmeDurumu_label.setObjectName("kilitlenmeDurumu_label")
        self.hedefMX_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.hedefMX_label.setGeometry(QtCore.QRect(120, 250, 171, 16))
        self.hedefMX_label.setObjectName("hedefMX_label")
        self.hedefMY_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.hedefMY_label.setGeometry(QtCore.QRect(120, 270, 171, 16))
        self.hedefMY_label.setObjectName("hedefMY_label")
        self.hedefGenislik_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.hedefGenislik_label.setGeometry(QtCore.QRect(110, 290, 181, 16))
        self.hedefGenislik_label.setObjectName("hedefGenislik_label")
        self.hedefYukseklik_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.hedefYukseklik_label.setGeometry(QtCore.QRect(120, 310, 181, 16))
        self.hedefYukseklik_label.setObjectName("hedefYukseklik_label")
        self.gpsSaati_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.gpsSaati_label.setGeometry(QtCore.QRect(80, 330, 191, 16))
        self.gpsSaati_label.setObjectName("gpsSaati_label")
        self.ucusModu_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.ucusModu_label.setGeometry(QtCore.QRect(90, 370, 151, 16))
        self.ucusModu_label.setObjectName("ucusModu_label")
        self.telemetriSinyalK_label = QtWidgets.QLabel(self.ucusBilgisi_groupBox)
        self.telemetriSinyalK_label.setGeometry(QtCore.QRect(160, 390, 101, 16))
        self.telemetriSinyalK_label.setObjectName("telemetriSinyalK_label")
        self.harita_groupBox = QtWidgets.QGroupBox(self.tab)
        self.harita_groupBox.setGeometry(QtCore.QRect(340, 40, 701, 461))
        self.harita_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.harita_groupBox.setObjectName("harita_groupBox")
        self.kamera_groupBox = QtWidgets.QGroupBox(self.tab)
        self.kamera_groupBox.setGeometry(QtCore.QRect(1050, 40, 831, 641))
        self.kamera_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.kamera_groupBox.setObjectName("kamera_groupBox")
        self.sunucuB_groupBox = QtWidgets.QGroupBox(self.tab)
        self.sunucuB_groupBox.setGeometry(QtCore.QRect(340, 500, 701, 181))
        self.sunucuB_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.sunucuB_groupBox.setObjectName("sunucuB_groupBox")
        self.label_8 = QtWidgets.QLabel(self.sunucuB_groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 91, 20))
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.sunucuAdresi_lineEdit = QtWidgets.QLineEdit(self.sunucuB_groupBox)
        self.sunucuAdresi_lineEdit.setGeometry(QtCore.QRect(120, 30, 201, 22))
        self.sunucuAdresi_lineEdit.setStyleSheet("#lineEdit{\n"
"background-color: rgb(255, 231, 226);\n"
"}")
        self.sunucuAdresi_lineEdit.setObjectName("sunucuAdresi_lineEdit")
        self.label_9 = QtWidgets.QLabel(self.sunucuB_groupBox)
        self.label_9.setGeometry(QtCore.QRect(390, 30, 81, 20))
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.kAdi_lineEdit = QtWidgets.QLineEdit(self.sunucuB_groupBox)
        self.kAdi_lineEdit.setGeometry(QtCore.QRect(480, 30, 201, 22))
        self.kAdi_lineEdit.setStyleSheet("#lineEdit_2{\n"
"background-color: rgb(255, 231, 226);\n"
"}")
        self.kAdi_lineEdit.setObjectName("kAdi_lineEdit")
        self.label_10 = QtWidgets.QLabel(self.sunucuB_groupBox)
        self.label_10.setGeometry(QtCore.QRect(390, 70, 61, 20))
        self.label_10.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.sifre_lineEdit = QtWidgets.QLineEdit(self.sunucuB_groupBox)
        self.sifre_lineEdit.setGeometry(QtCore.QRect(480, 70, 201, 22))
        self.sifre_lineEdit.setStyleSheet("#lineEdit_3{\n"
"background-color: rgb(255, 231, 226);\n"
"}")
        self.sifre_lineEdit.setObjectName("sifre_lineEdit")
        self.sunucuBaglan_pushButton = QtWidgets.QPushButton(self.sunucuB_groupBox)
        self.sunucuBaglan_pushButton.setGeometry(QtCore.QRect(170, 120, 161, 31))
        self.sunucuBaglan_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Arka plan rengi siyah */\n"
"    color: #ffffff; /* Yazı rengi beyaz */\n"
"    border: 1px solid #cccccc; /* Kenarlık rengi gri */\n"
"    padding: 10px 20px; /* Butonun iç dolgusu */\n"
"    font-family: Arial, sans-serif; /* Yazı tipi */\n"
"    font-size: 10px; /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333; /* Fare ile üzerine gelindiğinde arka plan rengi koyu gri */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666666; /* Butona basıldığında arka plan rengi orta gri */\n"
"}\n"
"")
        self.sunucuBaglan_pushButton.setObjectName("sunucuBaglan_pushButton")
        self.label_29 = QtWidgets.QLabel(self.sunucuB_groupBox)
        self.label_29.setGeometry(QtCore.QRect(480, 140, 91, 16))
        self.label_29.setObjectName("label_29")
        self.durumKodu_label = QtWidgets.QLabel(self.sunucuB_groupBox)
        self.durumKodu_label.setGeometry(QtCore.QRect(570, 140, 71, 16))
        self.durumKodu_label.setObjectName("durumKodu_label")
        self.ucusModu_groupBox = QtWidgets.QGroupBox(self.tab)
        self.ucusModu_groupBox.setGeometry(QtCore.QRect(10, 470, 321, 291))
        self.ucusModu_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.ucusModu_groupBox.setObjectName("ucusModu_groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.ucusModu_groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.RTLmode_pushButton = QtWidgets.QPushButton(self.ucusModu_groupBox)
        self.RTLmode_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Arka plan rengi siyah */\n"
"    color: #ffffff; /* Yazı rengi beyaz */\n"
"    border: 1px solid #cccccc; /* Kenarlık rengi gri */\n"
"    padding: 10px 20px; /* Butonun iç dolgusu */\n"
"    font-family: Arial, sans-serif; /* Yazı tipi */\n"
"    font-size: 10px; /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333; /* Fare ile üzerine gelindiğinde arka plan rengi koyu gri */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666666; /* Butona basıldığında arka plan rengi orta gri */\n"
"}\n"
"")
        self.RTLmode_pushButton.setObjectName("RTLmode_pushButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.RTLmode_pushButton)
        self.GUIDEDmode_pushButton = QtWidgets.QPushButton(self.ucusModu_groupBox)
        self.GUIDEDmode_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Arka plan rengi siyah */\n"
"    color: #ffffff; /* Yazı rengi beyaz */\n"
"    border: 1px solid #cccccc; /* Kenarlık rengi gri */\n"
"    padding: 10px 20px; /* Butonun iç dolgusu */\n"
"    font-family: Arial, sans-serif; /* Yazı tipi */\n"
"    font-size: 10px; /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333; /* Fare ile üzerine gelindiğinde arka plan rengi koyu gri */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666666; /* Butona basıldığında arka plan rengi orta gri */\n"
"}\n"
"")
        self.GUIDEDmode_pushButton.setObjectName("GUIDEDmode_pushButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.GUIDEDmode_pushButton)
        self.AUTOmode_pushButton = QtWidgets.QPushButton(self.ucusModu_groupBox)
        self.AUTOmode_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Arka plan rengi siyah */\n"
"    color: #ffffff; /* Yazı rengi beyaz */\n"
"    border: 1px solid #cccccc; /* Kenarlık rengi gri */\n"
"    padding: 10px 20px; /* Butonun iç dolgusu */\n"
"    font-family: Arial, sans-serif; /* Yazı tipi */\n"
"    font-size: 10px; /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333; /* Fare ile üzerine gelindiğinde arka plan rengi koyu gri */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666666; /* Butona basıldığında arka plan rengi orta gri */\n"
"}\n"
"")
        self.AUTOmode_pushButton.setObjectName("AUTOmode_pushButton")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.AUTOmode_pushButton)
        self.MANUELmode_pushButton = QtWidgets.QPushButton(self.ucusModu_groupBox)
        self.MANUELmode_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Arka plan rengi siyah */\n"
"    color: #ffffff; /* Yazı rengi beyaz */\n"
"    border: 1px solid #cccccc; /* Kenarlık rengi gri */\n"
"    padding: 10px 20px; /* Butonun iç dolgusu */\n"
"    font-family: Arial, sans-serif; /* Yazı tipi */\n"
"    font-size: 10px; /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333; /* Fare ile üzerine gelindiğinde arka plan rengi koyu gri */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666666; /* Butona basıldığında arka plan rengi orta gri */\n"
"}")
        self.MANUELmode_pushButton.setObjectName("MANUELmode_pushButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.MANUELmode_pushButton)
        self.FBWA_pushButton = QtWidgets.QPushButton(self.ucusModu_groupBox)
        self.FBWA_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Arka plan rengi siyah */\n"
"    color: #ffffff; /* Yazı rengi beyaz */\n"
"    border: 1px solid #cccccc; /* Kenarlık rengi gri */\n"
"    padding: 10px 20px; /* Butonun iç dolgusu */\n"
"    font-family: Arial, sans-serif; /* Yazı tipi */\n"
"    font-size: 10px; /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333; /* Fare ile üzerine gelindiğinde arka plan rengi koyu gri */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666666; /* Butona basıldığında arka plan rengi orta gri */\n"
"}")
        self.FBWA_pushButton.setObjectName("FBWA_pushButton")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.FBWA_pushButton)
        self.FBWB_pushButton = QtWidgets.QPushButton(self.ucusModu_groupBox)
        self.FBWB_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Arka plan rengi siyah */\n"
"    color: #ffffff; /* Yazı rengi beyaz */\n"
"    border: 1px solid #cccccc; /* Kenarlık rengi gri */\n"
"    padding: 10px 20px; /* Butonun iç dolgusu */\n"
"    font-family: Arial, sans-serif; /* Yazı tipi */\n"
"    font-size: 10px; /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333; /* Fare ile üzerine gelindiğinde arka plan rengi koyu gri */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666666; /* Butona basıldığında arka plan rengi orta gri */\n"
"}")
        self.FBWB_pushButton.setObjectName("FBWB_pushButton")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.FBWB_pushButton)
        self.kamikaze_groupBox = QtWidgets.QGroupBox(self.tab)
        self.kamikaze_groupBox.setGeometry(QtCore.QRect(740, 680, 411, 241))
        self.kamikaze_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.kamikaze_groupBox.setObjectName("kamikaze_groupBox")
        self.kamikazeBaslangic_groupBox = QtWidgets.QGroupBox(self.kamikaze_groupBox)
        self.kamikazeBaslangic_groupBox.setGeometry(QtCore.QRect(10, 70, 181, 151))
        self.kamikazeBaslangic_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.kamikazeBaslangic_groupBox.setObjectName("kamikazeBaslangic_groupBox")
        self.label_56 = QtWidgets.QLabel(self.kamikazeBaslangic_groupBox)
        self.label_56.setGeometry(QtCore.QRect(10, 40, 55, 16))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.kamikazeBaslangic_groupBox)
        self.label_57.setGeometry(QtCore.QRect(10, 60, 55, 16))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.kamikazeBaslangic_groupBox)
        self.label_58.setGeometry(QtCore.QRect(10, 80, 55, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.kamikazeBaslangic_groupBox)
        self.label_59.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.label_59.setObjectName("label_59")
        self.kamikazeBasSaat_label = QtWidgets.QLabel(self.kamikazeBaslangic_groupBox)
        self.kamikazeBasSaat_label.setGeometry(QtCore.QRect(50, 40, 111, 16))
        self.kamikazeBasSaat_label.setObjectName("kamikazeBasSaat_label")
        self.kamikazeBasDakika_label = QtWidgets.QLabel(self.kamikazeBaslangic_groupBox)
        self.kamikazeBasDakika_label.setGeometry(QtCore.QRect(60, 60, 91, 16))
        self.kamikazeBasDakika_label.setObjectName("kamikazeBasDakika_label")
        self.kamikazeBasSaniye_label = QtWidgets.QLabel(self.kamikazeBaslangic_groupBox)
        self.kamikazeBasSaniye_label.setGeometry(QtCore.QRect(60, 80, 81, 16))
        self.kamikazeBasSaniye_label.setObjectName("kamikazeBasSaniye_label")
        self.kamikazeBasMilisaniye_label = QtWidgets.QLabel(self.kamikazeBaslangic_groupBox)
        self.kamikazeBasMilisaniye_label.setGeometry(QtCore.QRect(80, 100, 81, 16))
        self.kamikazeBasMilisaniye_label.setObjectName("kamikazeBasMilisaniye_label")
        self.kamikazeBitis_groupBox = QtWidgets.QGroupBox(self.kamikaze_groupBox)
        self.kamikazeBitis_groupBox.setGeometry(QtCore.QRect(210, 70, 191, 151))
        self.kamikazeBitis_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.kamikazeBitis_groupBox.setObjectName("kamikazeBitis_groupBox")
        self.label_64 = QtWidgets.QLabel(self.kamikazeBitis_groupBox)
        self.label_64.setGeometry(QtCore.QRect(10, 30, 55, 16))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.kamikazeBitis_groupBox)
        self.label_65.setGeometry(QtCore.QRect(10, 50, 55, 16))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.kamikazeBitis_groupBox)
        self.label_66.setGeometry(QtCore.QRect(10, 70, 55, 16))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.kamikazeBitis_groupBox)
        self.label_67.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_67.setObjectName("label_67")
        self.kamikazeBitSaat_label = QtWidgets.QLabel(self.kamikazeBitis_groupBox)
        self.kamikazeBitSaat_label.setGeometry(QtCore.QRect(50, 30, 111, 16))
        self.kamikazeBitSaat_label.setObjectName("kamikazeBitSaat_label")
        self.kamikazeBitDakika_label = QtWidgets.QLabel(self.kamikazeBitis_groupBox)
        self.kamikazeBitDakika_label.setGeometry(QtCore.QRect(60, 50, 111, 16))
        self.kamikazeBitDakika_label.setObjectName("kamikazeBitDakika_label")
        self.kamikazeBitSaniye_label = QtWidgets.QLabel(self.kamikazeBitis_groupBox)
        self.kamikazeBitSaniye_label.setGeometry(QtCore.QRect(60, 70, 111, 16))
        self.kamikazeBitSaniye_label.setObjectName("kamikazeBitSaniye_label")
        self.kamikazeBitMilisaniye_label = QtWidgets.QLabel(self.kamikazeBitis_groupBox)
        self.kamikazeBitMilisaniye_label.setGeometry(QtCore.QRect(80, 90, 101, 16))
        self.kamikazeBitMilisaniye_label.setObjectName("kamikazeBitMilisaniye_label")
        self.label = QtWidgets.QLabel(self.kamikaze_groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.kamikaze_groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.kamikaze_groupBox)
        self.label_4.setGeometry(QtCore.QRect(230, 20, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_20 = QtWidgets.QLabel(self.kamikaze_groupBox)
        self.label_20.setGeometry(QtCore.QRect(230, 40, 71, 20))
        self.label_20.setObjectName("label_20")
        self.kamikazeDurumu_label = QtWidgets.QLabel(self.kamikaze_groupBox)
        self.kamikazeDurumu_label.setGeometry(QtCore.QRect(140, 20, 55, 16))
        self.kamikazeDurumu_label.setObjectName("kamikazeDurumu_label")
        self.QrKodMetni_label = QtWidgets.QLabel(self.kamikaze_groupBox)
        self.QrKodMetni_label.setGeometry(QtCore.QRect(110, 40, 121, 16))
        self.QrKodMetni_label.setObjectName("QrKodMetni_label")
        self.QrEnlem_label = QtWidgets.QLabel(self.kamikaze_groupBox)
        self.QrEnlem_label.setGeometry(QtCore.QRect(300, 20, 101, 16))
        self.QrEnlem_label.setObjectName("QrEnlem_label")
        self.QrBoylam_label = QtWidgets.QLabel(self.kamikaze_groupBox)
        self.QrBoylam_label.setGeometry(QtCore.QRect(310, 40, 91, 16))
        self.QrBoylam_label.setObjectName("QrBoylam_label")
        self.kilitlenme_groupBox = QtWidgets.QGroupBox(self.tab)
        self.kilitlenme_groupBox.setGeometry(QtCore.QRect(1160, 680, 451, 241))
        self.kilitlenme_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.kilitlenme_groupBox.setObjectName("kilitlenme_groupBox")
        self.label_26 = QtWidgets.QLabel(self.kilitlenme_groupBox)
        self.label_26.setGeometry(QtCore.QRect(30, 20, 121, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.kilitlenme_groupBox)
        self.label_27.setGeometry(QtCore.QRect(220, 20, 101, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.kilitlenme_groupBox)
        self.label_28.setGeometry(QtCore.QRect(220, 40, 151, 16))
        self.label_28.setObjectName("label_28")
        self.kilitlenmeDurumu_label_2 = QtWidgets.QLabel(self.kilitlenme_groupBox)
        self.kilitlenmeDurumu_label_2.setGeometry(QtCore.QRect(150, 20, 55, 16))
        self.kilitlenmeDurumu_label_2.setObjectName("kilitlenmeDurumu_label_2")
        self.denemeSayisi_label = QtWidgets.QLabel(self.kilitlenme_groupBox)
        self.denemeSayisi_label.setGeometry(QtCore.QRect(320, 20, 55, 16))
        self.denemeSayisi_label.setObjectName("denemeSayisi_label")
        self.basariliKilitlenmeSayisi_label = QtWidgets.QLabel(self.kilitlenme_groupBox)
        self.basariliKilitlenmeSayisi_label.setGeometry(QtCore.QRect(370, 40, 41, 16))
        self.basariliKilitlenmeSayisi_label.setObjectName("basariliKilitlenmeSayisi_label")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.kilitlenme_groupBox)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 70, 431, 161))
        self.tableWidget_2.setStyleSheet("QTableWidget {\n"
"    background-color: black;\n"
"    color: white;\n"
"    gridline-color: white;\n"
"    font-size: 11px; /* Tablo hücrelerinin yazı boyutu */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: black;\n"
"    color: white;\n"
"    font-size: 11px; /* Başlık hücrelerinin yazı boyutu */\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: black;\n"
"}\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        self.hss_groupBox = QtWidgets.QGroupBox(self.tab)
        self.hss_groupBox.setGeometry(QtCore.QRect(340, 680, 391, 241))
        self.hss_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.hss_groupBox.setObjectName("hss_groupBox")
        self.hss_tableWidget = QtWidgets.QTableWidget(self.hss_groupBox)
        self.hss_tableWidget.setGeometry(QtCore.QRect(10, 30, 371, 201))
        self.hss_tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: black;\n"
"    color: white;\n"
"    gridline-color: white;\n"
"    font-size: 11px; /* Tablo hücrelerinin yazı boyutu */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: black;\n"
"    color: white;\n"
"    font-size: 11px; /* Başlık hücrelerinin yazı boyutu */\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: black;\n"
"}\n"
"")
        self.hss_tableWidget.setObjectName("hss_tableWidget")
        self.hss_tableWidget.setColumnCount(8)
        self.hss_tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.hss_tableWidget.setHorizontalHeaderItem(7, item)
        self.gorevBaslat_groupBox = QtWidgets.QGroupBox(self.tab)
        self.gorevBaslat_groupBox.setGeometry(QtCore.QRect(10, 760, 321, 161))
        self.gorevBaslat_groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.gorevBaslat_groupBox.setObjectName("gorevBaslat_groupBox")
        self.kamikazeGorevi_pushButton = QtWidgets.QPushButton(self.gorevBaslat_groupBox)
        self.kamikazeGorevi_pushButton.setGeometry(QtCore.QRect(30, 30, 261, 41))
        self.kamikazeGorevi_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Arka plan rengi siyah */\n"
"    color: #ffffff; /* Yazı rengi beyaz */\n"
"    border: 1px solid #cccccc; /* Kenarlık rengi gri */\n"
"    padding: 10px 20px; /* Butonun iç dolgusu */\n"
"    font-family: Arial, sans-serif; /* Yazı tipi */\n"
"    font-size: 10px; /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333; /* Fare ile üzerine gelindiğinde arka plan rengi koyu gri */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666666; /* Butona basıldığında arka plan rengi orta gri */\n"
"}\n"
"")
        self.kamikazeGorevi_pushButton.setObjectName("kamikazeGorevi_pushButton")
        self.kilitlenmeGorevi_pushButton = QtWidgets.QPushButton(self.gorevBaslat_groupBox)
        self.kilitlenmeGorevi_pushButton.setGeometry(QtCore.QRect(30, 80, 261, 41))
        self.kilitlenmeGorevi_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Arka plan rengi siyah */\n"
"    color: #ffffff; /* Yazı rengi beyaz */\n"
"    border: 1px solid #cccccc; /* Kenarlık rengi gri */\n"
"    padding: 10px 20px; /* Butonun iç dolgusu */\n"
"    font-family: Arial, sans-serif; /* Yazı tipi */\n"
"    font-size: 10px; /* Yazı boyutu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333; /* Fare ile üzerine gelindiğinde arka plan rengi koyu gri */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #666666; /* Butona basıldığında arka plan rengi orta gri */\n"
"}\n"
"")
        self.kilitlenmeGorevi_pushButton.setObjectName("kilitlenmeGorevi_pushButton")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(820, 10, 111, 16))
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.baglantiDurumu_pushButton = QtWidgets.QPushButton(self.tab)
        self.baglantiDurumu_pushButton.setGeometry(QtCore.QRect(930, 0, 111, 31))
        self.baglantiDurumu_pushButton.setStyleSheet("QPushButton#baglantiDurumu_pushButton {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"")
        self.baglantiDurumu_pushButton.setObjectName("baglantiDurumu_pushButton")
        self.dateTime_label = QtWidgets.QLabel(self.tab)
        self.dateTime_label.setGeometry(QtCore.QRect(1610, 0, 201, 21))
        self.dateTime_label.setStyleSheet("font-size: 15px; color: white; background-color: rgba(0, 0, 0, 0.5); border-radius: 10px;")
        self.dateTime_label.setText("")
        self.dateTime_label.setObjectName("dateTime_label")
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Create a QTimer to update the date and time every second
        self.timer = QTimer()
        self.timer.timeout.connect(self.updateDateTime)
        self.timer.start(1000)  # Update every second
    

    def updateDateTime(self):
        current_time = QDateTime.currentDateTime()
        self.dateTime_label.setText(current_time.toString("yyyy-MM-dd hh:mm:ss"))    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GÖKTULGA Yer Kontrol İstasyonu Yazılımı"))
        self.port_comboBox.setItemText(0, _translate("MainWindow", "TCP"))
        self.port_comboBox.setItemText(1, _translate("MainWindow", "UDP"))
        self.port_comboBox.setItemText(2, _translate("MainWindow", "COM3"))
        self.port_comboBox.setItemText(3, _translate("MainWindow", "COM4"))
        self.port_comboBox.setItemText(4, _translate("MainWindow", "COM5"))
        self.port_comboBox.setItemText(5, _translate("MainWindow", "COM6"))
        self.port_comboBox.setItemText(6, _translate("MainWindow", "COM11"))
        self.port_comboBox.setItemText(7, _translate("MainWindow", "COM12"))
        self.baud_comboBox.setItemText(0, _translate("MainWindow", "38400"))
        self.baud_comboBox.setItemText(1, _translate("MainWindow", "57600"))
        self.baud_comboBox.setItemText(2, _translate("MainWindow", "115200"))
        self.baglan_pushButton.setText(_translate("MainWindow", "BAĞLAN"))
        self.ucusBilgisi_groupBox.setTitle(_translate("MainWindow", "İHA Uçuş Bilgileri"))
        self.label_3.setText(_translate("MainWindow", "Yönelme (YAW) Açısı :"))
        self.label_11.setText(_translate("MainWindow", "Yatış (ROLL) Açısı :"))
        self.label_21.setText(_translate("MainWindow", "Telemetri Sinyal Kalitesi :"))
        self.label_5.setText(_translate("MainWindow", "Takım Numarası :"))
        self.label_13.setText(_translate("MainWindow", "Enlem :"))
        self.label_15.setText(_translate("MainWindow", "Boylam :"))
        self.label_14.setText(_translate("MainWindow", "İrtifa :"))
        self.label_12.setText(_translate("MainWindow", "Dikilme (PITCH) Açısı :"))
        self.label_32.setText(_translate("MainWindow", "Batarya Yüzdesi :"))
        self.label_16.setText(_translate("MainWindow", "Yer Hızı :"))
        self.label_31.setText(_translate("MainWindow", "Otonom Durumu :"))
        self.label_19.setText(_translate("MainWindow", "Kilitlenme Durumu :"))
        self.label_18.setText(_translate("MainWindow", "Uçuş Modu :"))
        self.label_22.setText(_translate("MainWindow", "Hedef Merkez X :"))
        self.label_23.setText(_translate("MainWindow", "Hedef Merkez Y :"))
        self.label_17.setText(_translate("MainWindow", "Hedef Genişlik :"))
        self.label_24.setText(_translate("MainWindow", "Hedef Yükseklik :"))
        self.label_25.setText(_translate("MainWindow", "GPS Saati :"))
        self.takimNo_label.setText(_translate("MainWindow", "_"))
        self.enlem_label.setText(_translate("MainWindow", "_"))
        self.boylam_label.setText(_translate("MainWindow", "_"))
        self.irtifa_label.setText(_translate("MainWindow", "_"))
        self.pitch_label.setText(_translate("MainWindow", "_"))
        self.yaw_label.setText(_translate("MainWindow", "_"))
        self.roll_label.setText(_translate("MainWindow", "_"))
        self.yerHizi_label.setText(_translate("MainWindow", "_"))
        self.batarya_label.setText(_translate("MainWindow", "_"))
        self.otonomDurumu_label.setText(_translate("MainWindow", "_"))
        self.kilitlenmeDurumu_label.setText(_translate("MainWindow", "_"))
        self.hedefMX_label.setText(_translate("MainWindow", "_"))
        self.hedefMY_label.setText(_translate("MainWindow", "_"))
        self.hedefGenislik_label.setText(_translate("MainWindow", "_"))
        self.hedefYukseklik_label.setText(_translate("MainWindow", "_"))
        self.gpsSaati_label.setText(_translate("MainWindow", "_"))
        self.ucusModu_label.setText(_translate("MainWindow", "_"))
        self.telemetriSinyalK_label.setText(_translate("MainWindow", "_"))
        self.harita_groupBox.setTitle(_translate("MainWindow", "Harita"))
        self.kamera_groupBox.setTitle(_translate("MainWindow", "Kamera Görüntüsü"))
        self.sunucuB_groupBox.setTitle(_translate("MainWindow", "Sunucu Bağlantısı"))
        self.label_8.setText(_translate("MainWindow", "Sunucu Adresi :"))
        self.label_9.setText(_translate("MainWindow", "Kullanıcı Adı :"))
        self.label_10.setText(_translate("MainWindow", "Şifre :"))
        self.sunucuBaglan_pushButton.setText(_translate("MainWindow", "SUNUCUYA BAĞLAN "))
        self.label_29.setText(_translate("MainWindow", "Durum Kodu :"))
        self.durumKodu_label.setText(_translate("MainWindow", "_"))
        self.ucusModu_groupBox.setTitle(_translate("MainWindow", "Uçuş Modu"))
        self.RTLmode_pushButton.setText(_translate("MainWindow", "RTL"))
        self.GUIDEDmode_pushButton.setText(_translate("MainWindow", "GUIDED"))
        self.AUTOmode_pushButton.setText(_translate("MainWindow", "AUTO"))
        self.MANUELmode_pushButton.setText(_translate("MainWindow", "MANUEL"))
        self.FBWA_pushButton.setText(_translate("MainWindow", "FBWA"))
        self.FBWB_pushButton.setText(_translate("MainWindow", "FBWB"))
        self.kamikaze_groupBox.setTitle(_translate("MainWindow", "Kamikaze Verileri"))
        self.kamikazeBaslangic_groupBox.setTitle(_translate("MainWindow", "Kamikaze Başlangıç Zamanı"))
        self.label_56.setText(_translate("MainWindow", "Saat :"))
        self.label_57.setText(_translate("MainWindow", "Dakika :"))
        self.label_58.setText(_translate("MainWindow", "Saniye :"))
        self.label_59.setText(_translate("MainWindow", "Milisaniye :"))
        self.kamikazeBasSaat_label.setText(_translate("MainWindow", "_"))
        self.kamikazeBasDakika_label.setText(_translate("MainWindow", "_"))
        self.kamikazeBasSaniye_label.setText(_translate("MainWindow", "_"))
        self.kamikazeBasMilisaniye_label.setText(_translate("MainWindow", "_"))
        self.kamikazeBitis_groupBox.setTitle(_translate("MainWindow", "Kamikaze Bitiş Zamanı"))
        self.label_64.setText(_translate("MainWindow", "Saat :"))
        self.label_65.setText(_translate("MainWindow", "Dakika :"))
        self.label_66.setText(_translate("MainWindow", "Saniye :"))
        self.label_67.setText(_translate("MainWindow", "Milisaniye :"))
        self.kamikazeBitSaat_label.setText(_translate("MainWindow", "_"))
        self.kamikazeBitDakika_label.setText(_translate("MainWindow", "_"))
        self.kamikazeBitSaniye_label.setText(_translate("MainWindow", "_"))
        self.kamikazeBitMilisaniye_label.setText(_translate("MainWindow", "_"))
        self.label.setText(_translate("MainWindow", "Kamikaze Durumu :"))
        self.label_2.setText(_translate("MainWindow", "QR Kod Metni :"))
        self.label_4.setText(_translate("MainWindow", "QR Enlem :"))
        self.label_20.setText(_translate("MainWindow", "QR Boylam :"))
        self.kamikazeDurumu_label.setText(_translate("MainWindow", "_"))
        self.QrKodMetni_label.setText(_translate("MainWindow", "_"))
        self.QrEnlem_label.setText(_translate("MainWindow", "_"))
        self.QrBoylam_label.setText(_translate("MainWindow", "_"))
        self.kilitlenme_groupBox.setTitle(_translate("MainWindow", "Kilitlenme Verileri"))
        self.label_26.setText(_translate("MainWindow", "Kilitlenme Durumu :"))
        self.label_27.setText(_translate("MainWindow", "Deneme Sayısı :"))
        self.label_28.setText(_translate("MainWindow", "Başarılı Kilitlenme Sayısı :"))
        self.kilitlenmeDurumu_label_2.setText(_translate("MainWindow", "_"))
        self.denemeSayisi_label.setText(_translate("MainWindow", "_"))
        self.basariliKilitlenmeSayisi_label.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Başlama Zamanı"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bitiş Zamanı"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kilitlenme Süresi"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1. Kilitlenme"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2. Kilitlenme"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3. Kilitlenme"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4. Kilitlenme"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5. Kilitlenme"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6. Kilitlenme"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7. Kilitlenme"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8. Kilitlenme"))
        self.hss_groupBox.setTitle(_translate("MainWindow", "Hava Savunma Sistemi Koordinatları"))
        item = self.hss_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Enlem"))
        item = self.hss_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Boylam"))
        item = self.hss_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yarıçap"))
        item = self.hss_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID 1"))
        item = self.hss_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID 2"))
        item = self.hss_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID 3"))
        item = self.hss_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ID 4"))
        item = self.hss_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ID 5"))
        item = self.hss_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ID 6"))
        item = self.hss_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ID 7"))
        item = self.hss_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "ID 8"))
        self.gorevBaslat_groupBox.setTitle(_translate("MainWindow", "Görev Başlat"))
        self.kamikazeGorevi_pushButton.setText(_translate("MainWindow", "KAMİKAZE GÖREVİ"))
        self.kilitlenmeGorevi_pushButton.setText(_translate("MainWindow", "KİLİTLENME GÖREVİ"))
        self.label_6.setText(_translate("MainWindow", "Bağlantı Durumu :"))
        self.baglantiDurumu_pushButton.setText(_translate("MainWindow", "BAŞARISIZ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "GÖKTULGA İHA YER KONTROL ARAYÜZÜ"))
import arayuzQT_rc


if __name__ == "__main__":
    import sys
    from PyQt5.QtCore import QTimer, QDateTime  # Import QTimer and QDateTime
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
